const KEY2ELEMENT = new WeakMap();
const NODE2KEY = new WeakMap();
const NODE2INDEX = new WeakMap();
const NODE2PARENT = new WeakMap();
const NODE2ELEMENT = new WeakMap();
const ELEMENT2NODE = new WeakMap();
const EDITOR_TO_WINDOW = new WeakMap();
const EDITOR_TO_USER_SELECTION = new WeakMap();

export {KEY2ELEMENT, NODE2ELEMENT, NODE2INDEX, NODE2PARENT, ELEMENT2NODE, NODE2KEY, EDITOR_TO_WINDOW, EDITOR_TO_USER_SELECTION};
